# Generated by Django 5.0.6 on 2024-07-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recycler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recycler_id', models.PositiveSmallIntegerField()),
                ('recyler_name', models.CharField(max_length=20)),
                ('recycler_email', models.EmailField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('business_name', models.CharField(max_length=20)),
                ('mode_of_payment', models.CharField(max_length=20)),
            ],
        ),
    ]
